import { computeVisibleStateForAgent, findAgentById, type AgentVisibleState, type MarketState } from "@agents-marketplace/engine";

type RuntimeConfig = {
  agentRuntimeMode: string;
  ollamaBaseUrl: string;
  ollamaModel: string;
};

type StreamCallbacks = {
  onStart?: () => void;
  onToken?: (chunk: string, aggregate: string) => void;
  onComplete?: (aggregate: string) => void;
  onError?: (message: string) => void;
};

type CompactContext = {
  self: AgentVisibleState["self"];
  publicAgents: AgentVisibleState["publicAgents"];
  openOffers: AgentVisibleState["openOffers"];
  recentAnnouncements: AgentVisibleState["publicAnnouncements"];
  recentWhispers: AgentVisibleState["privateWhispers"];
  recentTrades: AgentVisibleState["publicTradeEvents"];
};

type InfoToolRequest = {
  tool: "announcement_mentions" | "whisper_history" | "trade_feedback";
  query?: string;
  agentId?: string;
};

export type AnnouncementResult = {
  content: string | null;
  trace: string;
};

export type WhisperStartResult = {
  whisper: {
    targetAgentId: string;
    message: string;
  } | null;
  trace: string;
};

export type WhisperReplyResult = {
  message: string | null;
  trace: string;
};

export type TradeProposalResult =
  | {
      kind: "pass";
      trace: string;
    }
  | {
      kind: "done";
      trace: string;
    }
  | {
      kind: "proposal";
      proposal: {
        targetAgentId: string;
        giveItemIds: string[];
        requestItemIds: string[];
        cashFromProposer: number;
        message: string;
      };
      trace: string;
    };

export type TradeResponseResult = {
  decision: "accept" | "reject";
  reason: string;
  trace: string;
};

export class AgentRuntime {
  constructor(private readonly runtimeConfig: RuntimeConfig) {}

  async warmModel() {
    if (this.runtimeConfig.agentRuntimeMode !== "ollama") {
      return "Heuristic runtime selected via configuration.";
    }

    const response = await fetch(`${this.runtimeConfig.ollamaBaseUrl}/api/chat`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: this.runtimeConfig.ollamaModel,
        messages: [],
        stream: false
      })
    });

    if (!response.ok) {
      throw new Error(`Ollama warm-up failed with ${response.status}`);
    }

    return `Warm-loaded ${this.runtimeConfig.ollamaModel} via Ollama.`;
  }

  async generateAnnouncement(state: MarketState, agentId: string, callbacks?: StreamCallbacks): Promise<AnnouncementResult> {
    const agent = findAgentById(state, agentId);

    if (!agent) {
      return { content: null, trace: "Agent missing from state." };
    }

    if (this.runtimeConfig.agentRuntimeMode !== "ollama") {
      return { content: heuristicAnnouncement(state, agentId), trace: "Heuristic announcement selected." };
    }

    const visibleState = computeVisibleStateForAgent(state, agentId);
    const compact = buildCompactContext(visibleState);

    try {
      const summary = await this.generateSummary(agentId, "announcement", compact);
      const response = await this.resolveWithInfoRequests(
        agentId,
        compact,
        summary,
        "Announcement phase. Return PASS or a short announcement sentence.",
        callbacks
      );

      if (isPass(response)) {
        return { content: null, trace: "Announcement phase passed." };
      }

      return {
        content: response.trim(),
        trace: "Announcement generated by Ollama."
      };
    } catch (error) {
      callbacks?.onError?.(toMessage(error));
      return {
        content: heuristicAnnouncement(state, agentId),
        trace: `Fell back to heuristic announcement: ${toMessage(error)}`
      };
    }
  }

  async generateWhisperStart(
    state: MarketState,
    agentId: string,
    unavailableTargets: string[],
    callbacks?: StreamCallbacks
  ): Promise<WhisperStartResult> {
    if (this.runtimeConfig.agentRuntimeMode !== "ollama") {
      return {
        whisper: heuristicWhisperStart(state, agentId, unavailableTargets),
        trace: "Heuristic whisper start selected."
      };
    }

    const visibleState = computeVisibleStateForAgent(state, agentId);
    const compact = buildCompactContext(visibleState);

    try {
      const summary = await this.generateSummary(agentId, "whisper start", {
        ...compact,
        unavailableTargets
      });
      const response = await this.resolveWithInfoRequests(
        agentId,
        compact,
        summary,
        `Whisper start phase. Unavailable targets this tick: ${unavailableTargets.join(", ") || "none"}. Return PASS or JSON like {"targetAgentId":"iara","message":"..."}.`,
        callbacks
      );

      if (isPass(response)) {
        return { whisper: null, trace: "Whisper start phase passed." };
      }

      const payload = extractJson(response);
      if (!payload || typeof payload.targetAgentId !== "string" || typeof payload.message !== "string") {
        throw new Error("Invalid whisper start payload.");
      }

      return {
        whisper: {
          targetAgentId: payload.targetAgentId,
          message: payload.message.trim()
        },
        trace: "Whisper start generated by Ollama."
      };
    } catch (error) {
      callbacks?.onError?.(toMessage(error));
      return {
        whisper: heuristicWhisperStart(state, agentId, unavailableTargets),
        trace: `Fell back to heuristic whisper start: ${toMessage(error)}`
      };
    }
  }

  async generateWhisperReply(
    state: MarketState,
    agentId: string,
    counterpartId: string,
    transcript: Array<{ speakerId: string; message: string }>,
    callbacks?: StreamCallbacks
  ): Promise<WhisperReplyResult> {
    if (this.runtimeConfig.agentRuntimeMode !== "ollama") {
      return {
        message: heuristicWhisperReply(state, agentId, counterpartId, transcript),
        trace: "Heuristic whisper reply selected."
      };
    }

    const visibleState = computeVisibleStateForAgent(state, agentId);
    const compact = buildCompactContext(visibleState);

    try {
      const summary = await this.generateSummary(agentId, "whisper reply", {
        ...compact,
        counterpartId,
        transcript
      });
      const response = await this.resolveWithInfoRequests(
        agentId,
        compact,
        summary,
        `Whisper reply phase with ${counterpartId}. Return PASS or a short reply. You may return plain text or JSON like {"message":"..."}.`,
        callbacks
      );

      if (isPass(response)) {
        return { message: null, trace: "Whisper reply passed." };
      }

      const payload = extractJson(response);
      if (payload && typeof payload.message === "string") {
        return {
          message: payload.message.trim(),
          trace: "Whisper reply generated by Ollama."
        };
      }

      return {
        message: response.trim(),
        trace: "Whisper reply generated by Ollama."
      };
    } catch (error) {
      callbacks?.onError?.(toMessage(error));
      return {
        message: heuristicWhisperReply(state, agentId, counterpartId, transcript),
        trace: `Fell back to heuristic whisper reply: ${toMessage(error)}`
      };
    }
  }

  async generateTradeProposal(state: MarketState, agentId: string, callbacks?: StreamCallbacks): Promise<TradeProposalResult> {
    if (this.runtimeConfig.agentRuntimeMode !== "ollama") {
      return heuristicTradeProposal(state, agentId);
    }

    const visibleState = computeVisibleStateForAgent(state, agentId);
    const compact = buildCompactContext(visibleState);

    try {
      const summary = await this.generateSummary(agentId, "trade proposal", compact);
      const response = await this.resolveWithInfoRequests(
        agentId,
        compact,
        summary,
        'Trade proposal phase. Return DONE, PASS, or JSON like {"targetAgentId":"toma","giveItemIds":[...],"requestItemIds":[...],"cashFromProposer":0,"message":"..."}. Only ensure the offer is valid from your own perspective.',
        callbacks
      );

      if (isDone(response)) {
        return {
          kind: "done",
          trace: "Agent declared done trading."
        };
      }

      if (isPass(response)) {
        return {
          kind: "pass",
          trace: "Trade proposal phase passed."
        };
      }

      const payload = extractJson(response);

      if (
        !payload ||
        typeof payload.targetAgentId !== "string" ||
        !Array.isArray(payload.giveItemIds) ||
        !Array.isArray(payload.requestItemIds) ||
        typeof payload.cashFromProposer !== "number" ||
        typeof payload.message !== "string"
      ) {
        throw new Error("Invalid trade proposal payload.");
      }

      return {
        kind: "proposal",
        proposal: {
          targetAgentId: payload.targetAgentId,
          giveItemIds: payload.giveItemIds.filter((value): value is string => typeof value === "string"),
          requestItemIds: payload.requestItemIds.filter((value): value is string => typeof value === "string"),
          cashFromProposer: payload.cashFromProposer,
          message: payload.message.trim()
        },
        trace: "Trade proposal generated by Ollama."
      };
    } catch (error) {
      callbacks?.onError?.(toMessage(error));
      return heuristicTradeProposal(state, agentId, `Fell back to heuristic trade proposal: ${toMessage(error)}`);
    }
  }

  async generateTradeResponse(
    state: MarketState,
    targetAgentId: string,
    offer: {
      fromAgentId: string;
      giveItemIds: string[];
      requestItemIds: string[];
      cashFromProposer: number;
      message: string;
    },
    callbacks?: StreamCallbacks
  ): Promise<TradeResponseResult> {
    if (this.runtimeConfig.agentRuntimeMode !== "ollama") {
      return heuristicTradeResponse(state, targetAgentId, offer);
    }

    const visibleState = computeVisibleStateForAgent(state, targetAgentId);
    const compact = buildCompactContext(visibleState);

    try {
      const summary = await this.generateSummary(targetAgentId, "trade response", {
        ...compact,
        offer
      });
      const response = await this.resolveWithInfoRequests(
        targetAgentId,
        compact,
        summary,
        "Trade response phase. Return ACCEPT to accept the offer. Otherwise return a rejection reason in plain text.",
        callbacks
      );

      if (isAccept(response)) {
        return {
          decision: "accept",
          reason: "Accepted by Ollama.",
          trace: "Trade response generated by Ollama."
        };
      }

      return {
        decision: "reject",
        reason: response.trim() || "No reason provided.",
        trace: "Trade response generated by Ollama."
      };
    } catch (error) {
      callbacks?.onError?.(toMessage(error));
      return heuristicTradeResponse(state, targetAgentId, offer, `Fell back to heuristic trade response: ${toMessage(error)}`);
    }
  }

  private async resolveWithInfoRequests(
    agentId: string,
    visibleContext: CompactContext,
    summary: string,
    finalInstruction: string,
    callbacks?: StreamCallbacks
  ) {
    const toolResults: string[] = [];

    for (let attempt = 0; attempt < 3; attempt += 1) {
      const response = await this.completePrompt(
        buildActionPrompt(agentId, summary, visibleContext, toolResults, finalInstruction),
        callbacks
      );

      const infoRequest = parseInfoToolRequest(response);
      if (!infoRequest) {
        return response;
      }

      toolResults.push(executeInfoTool(visibleContext, agentId, infoRequest));
    }

    throw new Error("Agent exhausted its information request budget.");
  }

  private async generateSummary(agentId: string, phase: string, compactContext: unknown) {
    if (this.runtimeConfig.agentRuntimeMode !== "ollama") {
      return `You are ${agentId}. Focus on what you directly know and avoid assuming hidden information.`;
    }

    const response = await this.completePrompt(
      [
        `Create a short imperfect-information summary for ${agentId} during the ${phase} phase.`,
        "Only summarize what this agent could reasonably know from the provided context.",
        "Do not infer hidden budgets, hidden inventory, or hidden valuations.",
        "Keep it under 90 words.",
        JSON.stringify(compactContext, null, 2)
      ].join("\n\n")
    );

    return response.trim();
  }

  private async completePrompt(prompt: string, callbacks?: StreamCallbacks) {
    callbacks?.onStart?.();

    const response = await fetch(`${this.runtimeConfig.ollamaBaseUrl}/api/chat`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: this.runtimeConfig.ollamaModel,
        stream: true,
        keep_alive: "30m",
        messages: [
          {
            role: "system",
            content: buildSystemPrompt()
          },
          {
            role: "user",
            content: prompt
          }
        ],
        options: {
          temperature: 0.9
        }
      })
    });

    if (!response.ok) {
      throw new Error(`Ollama returned ${response.status}`);
    }

    if (!response.body) {
      throw new Error("Ollama returned no response body.");
    }

    return readStreamedContent(response.body, callbacks);
  }
}

function buildSystemPrompt() {
  return [
    "You are a trading agent in a repeated market simulation.",
    "Inventories, budgets, and valuations are private.",
    "Announcements are public.",
    "Whispers are private between the two participants.",
    "You may bluff in dialogue.",
    "Be concise and stay in character.",
    "If you need more information, request a tool exactly in JSON.",
    "When told to PASS, DONE, or ACCEPT, return exactly that word if that is your choice."
  ].join(" ");
}

function buildCompactContext(visibleState: AgentVisibleState): CompactContext {
  return {
    self: visibleState.self,
    publicAgents: visibleState.publicAgents,
    openOffers: visibleState.openOffers.slice(0, 8),
    recentAnnouncements: visibleState.publicAnnouncements.slice(0, 8),
    recentWhispers: visibleState.privateWhispers.slice(0, 8),
    recentTrades: visibleState.publicTradeEvents.slice(0, 8)
  };
}

function buildActionPrompt(
  agentId: string,
  summary: string,
  visibleContext: CompactContext,
  toolResults: string[],
  finalInstruction: string
) {
  return [
    `Agent: ${agentId}`,
    finalInstruction,
    "You may first request one of these tools, using JSON only:",
    '- {"tool":"announcement_mentions","query":"solar-lens"}',
    '- {"tool":"whisper_history","agentId":"toma"}',
    '- {"tool":"trade_feedback","query":"repair-kit"}',
    "If you already have enough information, respond with the final action instead.",
    `Summary:\n${summary}`,
    `Visible context:\n${JSON.stringify(visibleContext, null, 2)}`,
    toolResults.length > 0 ? `Tool results:\n${toolResults.join("\n\n")}` : "Tool results: none yet."
  ].join("\n\n");
}

function executeInfoTool(visibleContext: CompactContext, agentId: string, request: InfoToolRequest) {
  switch (request.tool) {
    case "announcement_mentions": {
      const query = (request.query ?? "").toLowerCase().trim();
      const matches = visibleContext.recentAnnouncements.filter((event) => event.content.toLowerCase().includes(query));
      return formatToolResult(
        "announcement_mentions",
        matches.map((event) => `R${event.round}: ${event.content}`)
      );
    }
    case "whisper_history": {
      const targetAgentId = request.agentId ?? "";
      const matches = visibleContext.recentWhispers.filter(
        (event) =>
          event.actorAgentId === targetAgentId ||
          event.targetAgentId === targetAgentId
      );
      return formatToolResult(
        "whisper_history",
        matches.map((event) => `R${event.round}: ${event.content}`)
      );
    }
    case "trade_feedback": {
      const query = (request.query ?? request.agentId ?? agentId).toLowerCase().trim();
      const matches = visibleContext.recentTrades.filter((event) => event.content.toLowerCase().includes(query));
      return formatToolResult(
        "trade_feedback",
        matches.map((event) => `R${event.round}: ${event.content}`)
      );
    }
    default:
      return formatToolResult("unknown_tool", ["Unsupported tool request."]);
  }
}

function formatToolResult(tool: string, lines: string[]) {
  return [`Tool result: ${tool}`, ...(lines.length > 0 ? lines.slice(0, 6) : ["No recent matches found."])].join("\n");
}

function parseInfoToolRequest(value: string): InfoToolRequest | null {
  const payload = extractJson(value);

  if (!payload || typeof payload.tool !== "string") {
    return null;
  }

  if (
    payload.tool !== "announcement_mentions" &&
    payload.tool !== "whisper_history" &&
    payload.tool !== "trade_feedback"
  ) {
    return null;
  }

  return {
    tool: payload.tool,
    query: typeof payload.query === "string" ? payload.query : undefined,
    agentId: typeof payload.agentId === "string" ? payload.agentId : undefined
  };
}

function heuristicAnnouncement(state: MarketState, agentId: string) {
  const agent = findAgentById(state, agentId);
  if (!agent) {
    return null;
  }

  return `I am listening for opportunities that move ${agent.wishlist[0] ?? "value"} today.`;
}

function heuristicWhisperStart(state: MarketState, agentId: string, unavailableTargets: string[]) {
  const visibleState = computeVisibleStateForAgent(state, agentId);
  const target = visibleState.publicAgents.find(
    (candidate) => candidate.id !== agentId && !unavailableTargets.includes(candidate.id)
  );

  if (!target) {
    return null;
  }

  return {
    targetAgentId: target.id,
    message: "I think we can help each other if you move quickly."
  };
}

function heuristicWhisperReply(
  _state: MarketState,
  _agentId: string,
  _counterpartId: string,
  transcript: Array<{ speakerId: string; message: string }>
) {
  return transcript.length >= 2 ? null : "Maybe. What exactly are you aiming to get?";
}

function heuristicTradeProposal(state: MarketState, agentId: string, trace = "Heuristic trade proposal selected."): TradeProposalResult {
  const agent = findAgentById(state, agentId);

  if (!agent) {
    return { kind: "done", trace: "Agent missing from state." };
  }

  for (const wantedItemId of agent.wishlist) {
    if (agent.inventory.includes(wantedItemId)) {
      continue;
    }

    const owner = state.agents.find(
      (candidate) => candidate.id !== agentId && candidate.inventory.includes(wantedItemId)
    );

    if (!owner) {
      continue;
    }

    const giveItemId = [...agent.inventory].sort((left, right) => agent.valuations[left] - agent.valuations[right])[0];

    return {
      kind: "proposal",
      proposal: {
        targetAgentId: owner.id,
        giveItemIds: giveItemId ? [giveItemId] : [],
        requestItemIds: [wantedItemId],
        cashFromProposer: Math.max(0, Math.min(agent.budget, 8)),
        message: "This is clean and fast if you want to close."
      },
      trace
    };
  }

  return {
    kind: "done",
    trace
  };
}

function heuristicTradeResponse(
  state: MarketState,
  targetAgentId: string,
  offer: {
    fromAgentId: string;
    giveItemIds: string[];
    requestItemIds: string[];
    cashFromProposer: number;
    message: string;
  },
  trace = "Heuristic trade response selected."
): TradeResponseResult {
  const target = findAgentById(state, targetAgentId);

  if (!target) {
    return {
      decision: "reject",
      reason: "I cannot evaluate this right now.",
      trace: "Target missing from state."
    };
  }

  const gain = offer.giveItemIds.reduce((sum, itemId) => sum + (target.valuations[itemId] ?? 0), 0) + offer.cashFromProposer;
  const loss = offer.requestItemIds.reduce((sum, itemId) => sum + (target.valuations[itemId] ?? 0), 0);

  if (gain >= loss) {
    return {
      decision: "accept",
      reason: "Accepted by heuristic.",
      trace
    };
  }

  return {
    decision: "reject",
    reason: "I am not interested at that price anymore.",
    trace
  };
}

function isPass(value: string) {
  return value.trim().toUpperCase() === "PASS";
}

function isDone(value: string) {
  return value.trim().toUpperCase() === "DONE";
}

function isAccept(value: string) {
  return value.trim().toUpperCase() === "ACCEPT";
}

function extractJson(value: string) {
  const trimmed = value.trim();

  if (!trimmed.includes("{")) {
    return null;
  }

  const start = trimmed.indexOf("{");
  const end = trimmed.lastIndexOf("}");

  if (start === -1 || end === -1 || end <= start) {
    return null;
  }

  try {
    return JSON.parse(trimmed.slice(start, end + 1)) as Record<string, unknown>;
  } catch {
    return null;
  }
}

function toMessage(error: unknown) {
  return error instanceof Error ? error.message : "Unknown runtime error";
}

async function readStreamedContent(body: ReadableStream<Uint8Array>, callbacks?: StreamCallbacks) {
  const reader = body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  let aggregate = "";

  while (true) {
    const { value, done } = await reader.read();

    if (done) {
      break;
    }

    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split("\n");
    buffer = lines.pop() ?? "";

    for (const line of lines) {
      const trimmed = line.trim();

      if (!trimmed) {
        continue;
      }

      const payload = JSON.parse(trimmed) as {
        message?: {
          content?: string;
        };
        error?: string;
      };

      if (payload.error) {
        throw new Error(payload.error);
      }

      const chunk = payload.message?.content ?? "";
      if (chunk) {
        aggregate += chunk;
        callbacks?.onToken?.(chunk, aggregate);
      }
    }
  }

  if (buffer.trim()) {
    const payload = JSON.parse(buffer.trim()) as {
      message?: {
        content?: string;
      };
      error?: string;
    };

    if (payload.error) {
      throw new Error(payload.error);
    }

    const chunk = payload.message?.content ?? "";
    if (chunk) {
      aggregate += chunk;
      callbacks?.onToken?.(chunk, aggregate);
    }
  }

  callbacks?.onComplete?.(aggregate);
  return aggregate;
}
