import { computeVisibleStateForAgent, findAgentById, type AgentVisibleState, type MarketState } from "@agents-marketplace/engine";

type RuntimeConfig = {
  agentRuntimeMode: string;
  ollamaBaseUrl: string;
  ollamaModel: string;
};

type StreamCallbacks = {
  onStart?: () => void;
  onToken?: (chunk: string, aggregate: string) => void;
  onComplete?: (aggregate: string) => void;
  onError?: (message: string) => void;
};

type CompactContext = {
  self:
    | {
        id: string;
        name: string;
        budget: number;
        inventory: string[];
        wishlist: string[];
        valuations: Record<string, number>;
      }
    | null;
  publicAgents: Array<{
    id: string;
    name: string;
  }>;
  items: Array<{
    id: string;
    name: string;
  }>;
  openOffers: Array<{
    fromAgentId: string;
    toAgentId: string;
    giveItemIds: string[];
    requestItemIds: string[];
    cashFromProposer: number;
    message: string;
  }>;
  recentAnnouncements: string[];
  recentWhispers: Array<{
    withAgentId: string;
    text: string;
  }>;
  recentTrades: string[];
};

type InfoToolRequest = {
  tool: "announcement_mentions" | "whisper_history" | "trade_feedback";
  query?: string;
  agentId?: string;
};

type PromptOptions = {
  callbacks?: StreamCallbacks;
  systemPrompt?: string;
  temperature?: number;
};

type WhisperStartPayload = {
  targetAgentId: string;
  message: string;
};

type AnnouncementPayload = {
  content: string;
};

type WhisperReplyPayload = {
  message: string;
};

type TradeProposalPayload = {
  targetAgentId: string;
  giveItemIds: string[];
  requestItemIds: string[];
  cashFromProposer: number;
  message: string;
};

export type AnnouncementResult = {
  content: string | null;
  trace: string;
};

export type WhisperStartResult = {
  whisper: {
    targetAgentId: string;
    message: string;
  } | null;
  trace: string;
};

export type WhisperReplyResult = {
  message: string | null;
  trace: string;
};

export type TradeProposalResult =
  | {
      kind: "pass";
      trace: string;
    }
  | {
      kind: "done";
      trace: string;
    }
  | {
      kind: "proposal";
      proposal: {
        targetAgentId: string;
        giveItemIds: string[];
        requestItemIds: string[];
        cashFromProposer: number;
        message: string;
      };
      trace: string;
    };

export type TradeResponseResult = {
  decision: "accept" | "reject";
  reason: string;
  trace: string;
};

export class AgentRuntime {
  constructor(private readonly runtimeConfig: RuntimeConfig) {}

  async warmModel() {
    if (this.runtimeConfig.agentRuntimeMode !== "ollama") {
      return `Model warm-up skipped because runtime mode is ${this.runtimeConfig.agentRuntimeMode}.`;
    }

    const response = await fetch(`${this.runtimeConfig.ollamaBaseUrl}/api/chat`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: this.runtimeConfig.ollamaModel,
        messages: [],
        stream: false
      })
    });

    if (!response.ok) {
      throw new Error(`Ollama warm-up failed with ${response.status}`);
    }

    return `Warm-loaded ${this.runtimeConfig.ollamaModel} via Ollama.`;
  }

  async generateAnnouncement(state: MarketState, agentId: string, callbacks?: StreamCallbacks): Promise<AnnouncementResult> {
    const agent = findAgentById(state, agentId);

    if (!agent) {
      return { content: null, trace: "Agent missing from state." };
    }

    if (this.runtimeConfig.agentRuntimeMode !== "ollama") {
      return {
        content: null,
        trace: `Announcement skipped because runtime mode is ${this.runtimeConfig.agentRuntimeMode}.`
      };
    }

    const visibleState = computeVisibleStateForAgent(state, agentId);
    const compact = buildCompactContext(visibleState);

    try {
      const summary = await this.generateSummary(agentId, "announcement", compact);
      const response = await this.resolveWithInfoRequests(
        agentId,
        compact,
        summary,
        'Announcement phase. Return PASS or JSON like {"content":"short public announcement"}.',
        callbacks
      );

      const normalized = await this.normalizeAnnouncementResponse(agentId, compact, response);

      if (normalized.kind === "pass") {
        return { content: null, trace: "Announcement phase passed." };
      }

      return {
        content: normalized.payload.content,
        trace: normalized.repaired
          ? "Announcement translated from malformed Ollama output."
          : "Announcement generated by Ollama."
      };
    } catch (error) {
      callbacks?.onError?.(toMessage(error));
      return {
        content: null,
        trace: `Announcement failed: ${toMessage(error)}`
      };
    }
  }

  async generateWhisperStart(
    state: MarketState,
    agentId: string,
    unavailableTargets: string[],
    callbacks?: StreamCallbacks
  ): Promise<WhisperStartResult> {
    if (this.runtimeConfig.agentRuntimeMode !== "ollama") {
      return {
        whisper: null,
        trace: `Whisper start skipped because runtime mode is ${this.runtimeConfig.agentRuntimeMode}.`
      };
    }

    const visibleState = computeVisibleStateForAgent(state, agentId);
    const compact = buildCompactContext(visibleState);

    try {
      const summary = await this.generateSummary(agentId, "whisper start", {
        ...compact,
        unavailableTargets
      });
      const response = await this.resolveWithInfoRequests(
        agentId,
        compact,
        summary,
        `Whisper start phase. Unavailable targets this tick: ${unavailableTargets.join(", ") || "none"}. Return PASS or JSON like {"targetAgentId":"iara","message":"..."}.`,
        callbacks,
        { unavailableTargets }
      );

      const normalized = await this.normalizeWhisperStartResponse(agentId, compact, response);

      if (normalized.kind === "pass") {
        return { whisper: null, trace: "Whisper start phase passed." };
      }

      return {
        whisper: {
          targetAgentId: normalized.payload.targetAgentId,
          message: normalized.payload.message
        },
        trace: normalized.repaired
          ? "Whisper start translated from malformed Ollama output."
          : "Whisper start generated by Ollama."
      };
    } catch (error) {
      callbacks?.onError?.(toMessage(error));
      return {
        whisper: null,
        trace: `Whisper start failed: ${toMessage(error)}`
      };
    }
  }

  async generateWhisperReply(
    state: MarketState,
    agentId: string,
    counterpartId: string,
    transcript: Array<{ speakerId: string; message: string }>,
    callbacks?: StreamCallbacks
  ): Promise<WhisperReplyResult> {
    if (this.runtimeConfig.agentRuntimeMode !== "ollama") {
      return {
        message: null,
        trace: `Whisper reply skipped because runtime mode is ${this.runtimeConfig.agentRuntimeMode}.`
      };
    }

    const visibleState = computeVisibleStateForAgent(state, agentId);
    const compact = buildCompactContext(visibleState);

    try {
      const summary = await this.generateSummary(agentId, "whisper reply", {
        ...compact,
        counterpartId,
        transcript
      });
      const response = await this.resolveWithInfoRequests(
        agentId,
        compact,
        summary,
        `Whisper reply phase with ${counterpartId}. Return PASS or JSON like {"message":"short private reply"}.`,
        callbacks,
        { counterpartId, transcript }
      );

      const normalized = await this.normalizeWhisperReplyResponse(agentId, compact, response);

      if (normalized.kind === "pass") {
        return { message: null, trace: "Whisper reply passed." };
      }

      return {
        message: normalized.payload.message,
        trace: normalized.repaired
          ? "Whisper reply translated from malformed Ollama output."
          : "Whisper reply generated by Ollama."
      };
    } catch (error) {
      callbacks?.onError?.(toMessage(error));
      return {
        message: null,
        trace: `Whisper reply failed: ${toMessage(error)}`
      };
    }
  }

  async generateTradeProposal(state: MarketState, agentId: string, callbacks?: StreamCallbacks): Promise<TradeProposalResult> {
    if (this.runtimeConfig.agentRuntimeMode !== "ollama") {
      return {
        kind: "pass",
        trace: `Trade proposal skipped because runtime mode is ${this.runtimeConfig.agentRuntimeMode}.`
      };
    }

    const visibleState = computeVisibleStateForAgent(state, agentId);
    const compact = buildCompactContext(visibleState);

    try {
      const summary = await this.generateSummary(agentId, "trade proposal", compact);
      const response = await this.resolveWithInfoRequests(
        agentId,
        compact,
        summary,
        'Trade proposal phase. Return DONE, PASS, or JSON like {"targetAgentId":"toma","giveItemIds":[...],"requestItemIds":[...],"cashFromProposer":0,"message":"..."}. Only ensure the offer is valid from your own perspective.',
        callbacks
      );

      const normalized = await this.normalizeTradeProposalResponse(agentId, compact, response);

      if (normalized.kind === "done") {
        return {
          kind: "done",
          trace: "Agent declared done trading."
        };
      }

      if (normalized.kind === "pass") {
        return {
          kind: "pass",
          trace: "Trade proposal phase passed."
        };
      }

      return {
        kind: "proposal",
        proposal: {
          targetAgentId: normalized.payload.targetAgentId,
          giveItemIds: normalized.payload.giveItemIds,
          requestItemIds: normalized.payload.requestItemIds,
          cashFromProposer: normalized.payload.cashFromProposer,
          message: normalized.payload.message
        },
        trace: normalized.repaired
          ? "Trade proposal translated from malformed Ollama output."
          : "Trade proposal generated by Ollama."
      };
    } catch (error) {
      callbacks?.onError?.(toMessage(error));
      return {
        kind: "pass",
        trace: `Trade proposal failed: ${toMessage(error)}`
      };
    }
  }

  async generateTradeResponse(
    state: MarketState,
    targetAgentId: string,
    offer: {
      fromAgentId: string;
      giveItemIds: string[];
      requestItemIds: string[];
      cashFromProposer: number;
      message: string;
    },
    callbacks?: StreamCallbacks
  ): Promise<TradeResponseResult> {
    if (this.runtimeConfig.agentRuntimeMode !== "ollama") {
      return {
        decision: "reject",
        reason: `Trade response skipped because runtime mode is ${this.runtimeConfig.agentRuntimeMode}.`,
        trace: `Trade response skipped because runtime mode is ${this.runtimeConfig.agentRuntimeMode}.`
      };
    }

    const visibleState = computeVisibleStateForAgent(state, targetAgentId);
    const compact = buildCompactContext(visibleState);

    try {
      const summary = await this.generateSummary(targetAgentId, "trade response", {
        ...compact,
        offer
      });
      const response = await this.resolveWithInfoRequests(
        targetAgentId,
        compact,
        summary,
        'Trade response phase. Return ACCEPT or JSON like {"decision":"reject","reason":"short rejection reason"}.',
        callbacks,
        { offer }
      );

      const normalized = await this.normalizeTradeResponse(targetAgentId, compact, response);

      if (normalized.decision === "accept") {
        return {
          decision: "accept",
          reason: normalized.reason,
          trace: normalized.repaired
            ? "Trade response translated from malformed Ollama output."
            : "Trade response generated by Ollama."
        };
      }

      return {
        decision: "reject",
        reason: normalized.reason,
        trace: normalized.repaired
          ? "Trade response translated from malformed Ollama output."
          : "Trade response generated by Ollama."
      };
    } catch (error) {
      callbacks?.onError?.(toMessage(error));
      return {
        decision: "reject",
        reason: `Trade response failed: ${toMessage(error)}`,
        trace: `Trade response failed: ${toMessage(error)}`
      };
    }
  }

  private async resolveWithInfoRequests(
    agentId: string,
    visibleContext: CompactContext,
    summary: string,
    finalInstruction: string,
    callbacks?: StreamCallbacks,
    phaseContext?: unknown
  ) {
    const toolResults: string[] = [];
    const attemptedResponses: string[] = [];

    for (let attempt = 0; attempt < 3; attempt += 1) {
      const prompt = buildActionPrompt(agentId, summary, visibleContext, toolResults, finalInstruction, phaseContext);
      const response = await this.completePrompt(prompt, { callbacks });
      attemptedResponses.push(`Attempt ${attempt + 1}: ${sanitizeTraceSnippet(response)}`);

      const infoRequest = await this.normalizeInfoToolRequest(agentId, visibleContext, response);
      if (!infoRequest) {
        return response;
      }

      toolResults.push(executeInfoTool(visibleContext, agentId, infoRequest));
    }

    const forcedFinalPrompt = buildForcedFinalPrompt(agentId, summary, visibleContext, toolResults, finalInstruction, phaseContext);
    const forcedFinalResponse = await this.completePrompt(forcedFinalPrompt, { callbacks });
    attemptedResponses.push(`Forced final: ${sanitizeTraceSnippet(forcedFinalResponse)}`);

    if (parseInfoToolRequest(forcedFinalResponse)) {
      throw new Error(
        `Agent exhausted its information request budget and still requested a tool. Raw responses: ${attemptedResponses.join(" | ")}`
      );
    }

    return forcedFinalResponse;
  }

  private async generateSummary(agentId: string, phase: string, compactContext: unknown) {
    if (this.runtimeConfig.agentRuntimeMode !== "ollama") {
      return `You are ${agentId}. Focus on what you directly know and avoid assuming hidden information.`;
    }

    const response = await this.completePrompt(
      [
        `Create a short imperfect-information summary for ${agentId} during the ${phase} phase.`,
        "Only summarize what this agent could reasonably know from the provided context.",
        "Do not infer hidden budgets, hidden inventory, or hidden valuations.",
        JSON.stringify(compactContext, null, 2)
      ].join("\n\n"),
      {
        temperature: 0.6
      }
    );

    return response.trim();
  }

  private async normalizeInfoToolRequest(agentId: string, visibleContext: CompactContext, response: string) {
    const exact = parseInfoToolRequest(response);
    if (exact) {
      return exact;
    }

    if (!looksLikeToolRequest(response)) {
      return null;
    }

    const repaired = await this.completePrompt(
      buildToolRecoveryPrompt(agentId, visibleContext, response),
      {
        systemPrompt: buildRecoverySystemPrompt(),
        temperature: 0.1
      }
    );

    const normalized = repaired.trim().toUpperCase();
    if (normalized === "FINAL" || normalized === "INVALID") {
      return null;
    }

    return parseInfoToolRequest(repaired);
  }

  private async normalizeAnnouncementResponse(agentId: string, visibleContext: CompactContext, response: string) {
    if (isPass(response)) {
      return {
        kind: "pass" as const
      };
    }

    const payload = parseAnnouncementPayload(response);
    if (payload) {
      return {
        kind: "announcement" as const,
        payload,
        repaired: false
      };
    }

    const repaired = await this.completePrompt(
      buildAnnouncementRecoveryPrompt(agentId, visibleContext, response),
      {
        systemPrompt: buildRecoverySystemPrompt(),
        temperature: 0.1
      }
    );

    if (isPass(repaired)) {
      return {
        kind: "pass" as const
      };
    }

    const repairedPayload = parseAnnouncementPayload(repaired);
    if (!repairedPayload) {
      throw new Error("Invalid announcement payload.");
    }

    return {
      kind: "announcement" as const,
      payload: repairedPayload,
      repaired: true
    };
  }

  private async normalizeWhisperStartResponse(agentId: string, visibleContext: CompactContext, response: string) {
    if (isPass(response)) {
      return {
        kind: "pass" as const
      };
    }

    const payload = parseWhisperStartPayload(response);
    if (payload) {
      return {
        kind: "whisper" as const,
        payload,
        repaired: false
      };
    }

    const repaired = await this.completePrompt(
      buildWhisperStartRecoveryPrompt(agentId, visibleContext, response),
      {
        systemPrompt: buildRecoverySystemPrompt(),
        temperature: 0.1
      }
    );

    if (isPass(repaired)) {
      return {
        kind: "pass" as const
      };
    }

    const repairedPayload = parseWhisperStartPayload(repaired);
    if (!repairedPayload) {
      throw new Error("Invalid whisper start payload.");
    }

    return {
      kind: "whisper" as const,
      payload: repairedPayload,
      repaired: true
    };
  }

  private async normalizeWhisperReplyResponse(agentId: string, visibleContext: CompactContext, response: string) {
    if (isPass(response)) {
      return {
        kind: "pass" as const
      };
    }

    const payload = parseWhisperReplyPayload(response);
    if (payload) {
      return {
        kind: "reply" as const,
        payload,
        repaired: false
      };
    }

    const repaired = await this.completePrompt(
      buildWhisperReplyRecoveryPrompt(agentId, visibleContext, response),
      {
        systemPrompt: buildRecoverySystemPrompt(),
        temperature: 0.1
      }
    );

    if (isPass(repaired)) {
      return {
        kind: "pass" as const
      };
    }

    const repairedPayload = parseWhisperReplyPayload(repaired);
    if (!repairedPayload) {
      throw new Error("Invalid whisper reply payload.");
    }

    return {
      kind: "reply" as const,
      payload: repairedPayload,
      repaired: true
    };
  }

  private async normalizeTradeProposalResponse(agentId: string, visibleContext: CompactContext, response: string) {
    if (isDone(response)) {
      return {
        kind: "done" as const
      };
    }

    if (isPass(response)) {
      return {
        kind: "pass" as const
      };
    }

    const payload = parseTradeProposalPayload(response);
    if (payload) {
      return {
        kind: "proposal" as const,
        payload,
        repaired: false
      };
    }

    const repaired = await this.completePrompt(
      buildTradeProposalRecoveryPrompt(agentId, visibleContext, response),
      {
        systemPrompt: buildRecoverySystemPrompt(),
        temperature: 0.1
      }
    );

    if (isDone(repaired)) {
      return {
        kind: "done" as const
      };
    }

    if (isPass(repaired)) {
      return {
        kind: "pass" as const
      };
    }

    const repairedPayload = parseTradeProposalPayload(repaired);
    if (!repairedPayload) {
      throw new Error("Invalid trade proposal payload.");
    }

    return {
      kind: "proposal" as const,
      payload: repairedPayload,
      repaired: true
    };
  }

  private async normalizeTradeResponse(agentId: string, visibleContext: CompactContext, response: string) {
    const exact = parseTradeResponseDecision(response);
    if (exact) {
      return {
        decision: exact.decision,
        reason: exact.reason ?? (exact.decision === "accept" ? "Accepted by Ollama." : "No reason provided."),
        repaired: false
      };
    }

    if (isAccept(response)) {
      return {
        decision: "accept" as const,
        reason: "Accepted by Ollama.",
        repaired: false
      };
    }

    const repaired = await this.completePrompt(
      buildTradeResponseRecoveryPrompt(agentId, visibleContext, response),
      {
        systemPrompt: buildRecoverySystemPrompt(),
        temperature: 0.1
      }
    );

    const repairedDecision = parseTradeResponseDecision(repaired);
    if (repairedDecision) {
      return {
        decision: repairedDecision.decision,
        reason:
          repairedDecision.reason ??
          (repairedDecision.decision === "accept" ? "Accepted by translated Ollama response." : "No reason provided."),
        repaired: true
      };
    }

    if (isAccept(repaired)) {
      return {
        decision: "accept" as const,
        reason: "Accepted by translated Ollama response.",
        repaired: true
      };
    }

    throw new Error("Invalid trade response payload.");
  }

  private async completePrompt(prompt: string, options: PromptOptions = {}) {
    const systemPrompt = options.systemPrompt ?? buildSystemPrompt();
    options.callbacks?.onStart?.();

    const response = await fetch(`${this.runtimeConfig.ollamaBaseUrl}/api/chat`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: this.runtimeConfig.ollamaModel,
        stream: true,
        keep_alive: "30m",
        messages: [
          {
            role: "system",
            content: systemPrompt
          },
          {
            role: "user",
            content: prompt
          }
        ],
        options: {
          temperature: options.temperature ?? 0.9
        }
      })
    });

    if (!response.ok) {
      throw new Error(`Ollama returned ${response.status}`);
    }

    if (!response.body) {
      throw new Error("Ollama returned no response body.");
    }

    return readStreamedContent(response.body, options.callbacks);
  }
}

function buildSystemPrompt() {
  return [
    "You are a trading agent in a repeated market simulation.",
    "Every response is consumed by a strict machine parser.",
    "Any extra prose, labels, markdown fences, or multiple candidate outputs will be rejected.",
    "Inventories, budgets, and valuations are private.",
    "Announcements are public.",
    "Whispers are private between the two participants.",
    "You may bluff in dialogue.",
    "Be concise and stay in character.",
    "If you need more information, request a tool exactly in JSON.",
    "If a phase asks for JSON, return exactly one JSON object with no prose before or after it.",
    "Do not wrap JSON in markdown fences.",
    "When told to PASS, DONE, or ACCEPT, return exactly that word if that is your choice."
  ].join(" ");
}

function buildRecoverySystemPrompt() {
  return [
    "You translate messy agent output into one allowed machine-readable result.",
    "Return only the normalized result.",
    "Do not explain your reasoning.",
    "Do not add markdown fences.",
    "If the text cannot be mapped with high confidence, return INVALID."
  ].join(" ");
}

function buildCompactContext(visibleState: AgentVisibleState): CompactContext {
  return {
    self: visibleState.self
      ? {
          id: visibleState.self.id,
          name: visibleState.self.name,
          budget: visibleState.self.budget,
          inventory: visibleState.self.inventory,
          wishlist: visibleState.self.wishlist,
          valuations: visibleState.self.valuations
        }
      : null,
    publicAgents: visibleState.publicAgents.map((agent) => ({
      id: agent.id,
      name: agent.name
    })),
    items: visibleState.items.map((item) => ({
      id: item.id,
      name: item.name
    })),
    openOffers: visibleState.openOffers.slice(0, 8).map((offer) => ({
      fromAgentId: offer.fromAgentId,
      toAgentId: offer.toAgentId,
      giveItemIds: offer.giveItemIds,
      requestItemIds: offer.requestItemIds,
      cashFromProposer: offer.cashFromProposer,
      message: offer.message
    })),
    recentAnnouncements: visibleState.publicAnnouncements.slice(0, 8).map((event) => event.content.replace(/^.+? announced:\s*/, "")),
    recentWhispers: visibleState.privateWhispers.slice(0, 8).map((event) => ({
      withAgentId: event.actorAgentId === visibleState.self?.id ? event.targetAgentId ?? "unknown" : event.actorAgentId ?? "unknown",
      text: event.content.replace(/^.+?:\s*/, "")
    })),
    recentTrades: visibleState.publicTradeEvents.slice(0, 8).map((event) => event.content)
  };
}

function buildActionPrompt(
  agentId: string,
  summary: string,
  visibleContext: CompactContext,
  toolResults: string[],
  finalInstruction: string,
  phaseContext?: unknown
) {
  return [
    `Summary:\n${summary}`,
    `Visible context:\n${JSON.stringify(visibleContext, null, 2)}`,
    phaseContext ? `Phase context:\n${JSON.stringify(phaseContext, null, 2)}` : null,
    toolResults.length > 0 ? `Tool results:\n${toolResults.join("\n\n")}` : "Tool results: none yet.",
    "You may first request one of these tools, using JSON only:",
    '- {"tool":"announcement_mentions","query":"solar-lens"}',
    '- {"tool":"whisper_history","agentId":"toma"}',
    '- {"tool":"trade_feedback","query":"repair-kit"}',
    "Tool requests must be exact JSON with no surrounding prose.",
    "Return exactly one output only.",
    "Do not prefix with labels like JSON:, Answer:, Tool:, or Requesting tool:.",
    "Do not include explanations before or after the final JSON or keyword.",
    "Do not output multiple tool calls in one response.",
    "If you ask for a tool, do not also answer the phase in the same response.",
    "If you already have enough information, respond with the final action instead.",
    `Expected response format:\n${finalInstruction}`,
    buildIdentityFooter(agentId, visibleContext)
  ].filter(Boolean).join("\n\n");
}

function buildForcedFinalPrompt(
  agentId: string,
  summary: string,
  visibleContext: CompactContext,
  toolResults: string[],
  finalInstruction: string,
  phaseContext?: unknown
) {
  return [
    `Summary:\n${summary}`,
    `Visible context:\n${JSON.stringify(visibleContext, null, 2)}`,
    phaseContext ? `Phase context:\n${JSON.stringify(phaseContext, null, 2)}` : null,
    toolResults.length > 0 ? `Tool results:\n${toolResults.join("\n\n")}` : "Tool results: none yet.",
    "Your tool-request budget is exhausted.",
    "You must now choose the final action using only the information above.",
    "Do not ask for any tool.",
    "Return exactly one final output only.",
    "Do not include explanations before or after the final JSON or keyword.",
    `Expected response format:\n${finalInstruction}`,
    buildIdentityFooter(agentId, visibleContext)
  ].filter(Boolean).join("\n\n");
}

function executeInfoTool(visibleContext: CompactContext, agentId: string, request: InfoToolRequest) {
  switch (request.tool) {
    case "announcement_mentions": {
      const query = (request.query ?? "").toLowerCase().trim();
      const matches = visibleContext.recentAnnouncements.filter((text) => text.toLowerCase().includes(query));
      return formatToolResult(
        "announcement_mentions",
        matches
      );
    }
    case "whisper_history": {
      const targetAgentId = request.agentId ?? "";
      const matches = visibleContext.recentWhispers.filter(
        (event) => event.withAgentId === targetAgentId
      );
      return formatToolResult(
        "whisper_history",
        matches.map((event) => `${event.withAgentId}: ${event.text}`)
      );
    }
    case "trade_feedback": {
      const query = (request.query ?? request.agentId ?? agentId).toLowerCase().trim();
      const matches = visibleContext.recentTrades.filter((text) => text.toLowerCase().includes(query));
      return formatToolResult(
        "trade_feedback",
        matches
      );
    }
    default:
      return formatToolResult("unknown_tool", ["Unsupported tool request."]);
  }
}

function formatToolResult(tool: string, lines: string[]) {
  return [`Tool result: ${tool}`, ...(lines.length > 0 ? lines.slice(0, 6) : ["No recent matches found."])].join("\n");
}

function parseInfoToolRequest(value: string): InfoToolRequest | null {
  const payload = extractJson(value);

  if (!payload || typeof payload.tool !== "string") {
    return null;
  }

  if (
    payload.tool !== "announcement_mentions" &&
    payload.tool !== "whisper_history" &&
    payload.tool !== "trade_feedback"
  ) {
    return null;
  }

  return {
    tool: payload.tool,
    query: typeof payload.query === "string" ? payload.query : undefined,
    agentId: typeof payload.agentId === "string" ? payload.agentId : undefined
  };
}

function parseAnnouncementPayload(value: string): AnnouncementPayload | null {
  const payload = extractJson(value);

  if (!payload || typeof payload.content !== "string") {
    return null;
  }

  const content = payload.content.trim();
  return content ? { content } : null;
}

function parseWhisperStartPayload(value: string): WhisperStartPayload | null {
  const payload = extractJson(value);

  if (!payload || typeof payload.targetAgentId !== "string" || typeof payload.message !== "string") {
    return null;
  }

  const targetAgentId = payload.targetAgentId.trim();
  const message = payload.message.trim();

  if (!targetAgentId || !message) {
    return null;
  }

  return { targetAgentId, message };
}

function parseWhisperReplyPayload(value: string): WhisperReplyPayload | null {
  const payload = extractJson(value);

  if (!payload || typeof payload.message !== "string") {
    return null;
  }

  const message = payload.message.trim();
  return message ? { message } : null;
}

function parseTradeProposalPayload(value: string): TradeProposalPayload | null {
  const payload = extractJson(value);

  if (!payload || typeof payload.targetAgentId !== "string" || typeof payload.message !== "string") {
    return null;
  }

  const cashFromProposer = coerceNumber(payload.cashFromProposer);
  if (cashFromProposer === null) {
    return null;
  }

  const giveItemIds = coerceStringArray(payload.giveItemIds);
  const requestItemIds = coerceStringArray(payload.requestItemIds);
  const targetAgentId = payload.targetAgentId.trim();
  const message = payload.message.trim();

  if (!targetAgentId || !message || !giveItemIds || !requestItemIds) {
    return null;
  }

  return {
    targetAgentId,
    giveItemIds,
    requestItemIds,
    cashFromProposer,
    message
  };
}

function parseTradeResponseDecision(value: string) {
  const payload = extractJson(value);

  if (!payload || typeof payload.decision !== "string") {
    return null;
  }

  const decision = payload.decision.trim().toLowerCase();
  if (decision !== "accept" && decision !== "reject") {
    return null;
  }

  return {
    decision,
    reason: typeof payload.reason === "string" ? payload.reason.trim() : undefined
  };
}

function isPass(value: string) {
  return matchesControlWord(value, "PASS");
}

function isDone(value: string) {
  return matchesControlWord(value, "DONE");
}

function isAccept(value: string) {
  return matchesControlWord(value, "ACCEPT");
}

function matchesControlWord(value: string, word: string) {
  return new RegExp(`^${word}(?:\\b|\\s|[.!?,:;])`, "i").test(value.trim());
}

function extractJson(value: string) {
  const trimmed = value.trim();

  if (!trimmed.includes("{")) {
    return null;
  }

  const start = trimmed.indexOf("{");
  const end = trimmed.lastIndexOf("}");

  if (start === -1 || end === -1 || end <= start) {
    return null;
  }

  try {
    return JSON.parse(trimmed.slice(start, end + 1)) as Record<string, unknown>;
  } catch {
    return null;
  }
}

function toMessage(error: unknown) {
  return error instanceof Error ? error.message : "Unknown runtime error";
}

function sanitizeTraceSnippet(value: string) {
  return value.replace(/\s+/g, " ").trim().slice(0, 280) || "(empty response)";
}

function looksLikeToolRequest(value: string) {
  const normalized = value.toLowerCase();
  return (
    normalized.includes("tool") ||
    normalized.includes("whisper history") ||
    normalized.includes("announcement mentions") ||
    normalized.includes("trade feedback") ||
    normalized.includes("announcement_mentions") ||
    normalized.includes("whisper_history") ||
    normalized.includes("trade_feedback")
  );
}

function coerceNumber(value: unknown) {
  if (typeof value === "number" && Number.isFinite(value)) {
    return value;
  }

  if (typeof value === "string" && value.trim()) {
    const parsed = Number(value);
    return Number.isFinite(parsed) ? parsed : null;
  }

  return null;
}

function coerceStringArray(value: unknown) {
  if (Array.isArray(value)) {
    return value.filter((entry): entry is string => typeof entry === "string").map((entry) => entry.trim());
  }

  if (typeof value === "string" && value.trim()) {
    return [value.trim()];
  }

  return null;
}

function buildToolRecoveryPrompt(agentId: string, visibleContext: CompactContext, candidate: string) {
  return [
    `Normalize ${agentId}'s candidate response into a tool request only if it is clearly asking for a tool.`,
    "Return exactly one of these outputs:",
    '{"tool":"announcement_mentions","query":"solar-lens"}',
    '{"tool":"whisper_history","agentId":"toma"}',
    '{"tool":"trade_feedback","query":"repair-kit"}',
    "FINAL",
    "Return FINAL if the candidate is not asking for one of the tools.",
    "Do not output multiple tool requests.",
    `Known agents:\n${formatAgentDirectory(visibleContext)}`,
    `Known items:\n${formatItemDirectory(visibleContext)}`,
    `Visible context:\n${JSON.stringify(visibleContext, null, 2)}`,
    `Candidate output:\n${candidate}`
  ].join("\n\n");
}

function buildAnnouncementRecoveryPrompt(agentId: string, visibleContext: CompactContext, candidate: string) {
  return [
    `Normalize ${agentId}'s announcement candidate into one allowed output.`,
    "Return exactly one of these outputs:",
    "PASS",
    '{"content":"short public announcement"}',
    "INVALID",
    "The content must stay short and public-facing.",
    `Visible context:\n${JSON.stringify(visibleContext, null, 2)}`,
    `Candidate output:\n${candidate}`
  ].join("\n\n");
}

function buildWhisperStartRecoveryPrompt(agentId: string, visibleContext: CompactContext, candidate: string) {
  return [
    `Normalize ${agentId}'s whisper-start candidate into one allowed output.`,
    "Return exactly one of these outputs:",
    "PASS",
    '{"targetAgentId":"iara","message":"I think we can help each other if you move quickly."}',
    "INVALID",
    "Use an exact public agent id for targetAgentId.",
    `Known agents:\n${formatAgentDirectory(visibleContext)}`,
    `Candidate output:\n${candidate}`
  ].join("\n\n");
}

function buildWhisperReplyRecoveryPrompt(agentId: string, visibleContext: CompactContext, candidate: string) {
  return [
    `Normalize ${agentId}'s whisper-reply candidate into one allowed output.`,
    "Return exactly one of these outputs:",
    "PASS",
    '{"message":"short private reply"}',
    "INVALID",
    "The message must stay short and private.",
    `Visible context:\n${JSON.stringify(visibleContext, null, 2)}`,
    `Candidate output:\n${candidate}`
  ].join("\n\n");
}

function buildTradeProposalRecoveryPrompt(agentId: string, visibleContext: CompactContext, candidate: string) {
  return [
    `Normalize ${agentId}'s trade proposal candidate into one allowed output.`,
    "Return exactly one of these outputs:",
    "DONE",
    "PASS",
    '{"targetAgentId":"toma","giveItemIds":["saffron"],"requestItemIds":["repair-kit"],"cashFromProposer":8,"message":"Clean swap if you want speed."}',
    "INVALID",
    "Use exact public agent ids and exact item ids.",
    "Do not invent items or agents that are not listed below.",
    `Known agents:\n${formatAgentDirectory(visibleContext)}`,
    `Known items:\n${formatItemDirectory(visibleContext)}`,
    `Visible context:\n${JSON.stringify(visibleContext, null, 2)}`,
    `Candidate output:\n${candidate}`
  ].join("\n\n");
}

function buildTradeResponseRecoveryPrompt(agentId: string, visibleContext: CompactContext, candidate: string) {
  return [
    `Normalize ${agentId}'s trade-response candidate into one allowed output.`,
    "Return exactly one of these outputs:",
    "ACCEPT",
    '{"decision":"reject","reason":"short rejection reason"}',
    "INVALID",
    "Do not return plain text outside the JSON object.",
    `Visible context:\n${JSON.stringify(visibleContext, null, 2)}`,
    `Candidate output:\n${candidate}`
  ].join("\n\n");
}

function formatAgentDirectory(visibleContext: CompactContext) {
  return visibleContext.publicAgents.map((agent) => `- ${agent.id}: ${agent.name}`).join("\n");
}

function formatItemDirectory(visibleContext: CompactContext) {
  return visibleContext.items.map((item) => `- ${item.id}: ${item.name}`).join("\n");
}

function buildIdentityFooter(agentId: string, visibleContext: CompactContext) {
  return [
    `Agent ID: ${agentId}`,
    `Agent Name: ${visibleContext.self?.name ?? agentId}`,
    "Complete the response as this exact agent."
  ].join("\n");
}

async function readStreamedContent(body: ReadableStream<Uint8Array>, callbacks?: StreamCallbacks) {
  const reader = body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  let aggregate = "";

  while (true) {
    const { value, done } = await reader.read();

    if (done) {
      break;
    }

    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split("\n");
    buffer = lines.pop() ?? "";

    for (const line of lines) {
      const trimmed = line.trim();

      if (!trimmed) {
        continue;
      }

      const payload = JSON.parse(trimmed) as {
        message?: {
          content?: string;
        };
        error?: string;
      };

      if (payload.error) {
        throw new Error(payload.error);
      }

      const chunk = payload.message?.content ?? "";
      if (chunk) {
        aggregate += chunk;
        callbacks?.onToken?.(chunk, aggregate);
      }
    }
  }

  if (buffer.trim()) {
    const payload = JSON.parse(buffer.trim()) as {
      message?: {
        content?: string;
      };
      error?: string;
    };

    if (payload.error) {
      throw new Error(payload.error);
    }

    const chunk = payload.message?.content ?? "";
    if (chunk) {
      aggregate += chunk;
      callbacks?.onToken?.(chunk, aggregate);
    }
  }

  callbacks?.onComplete?.(aggregate);
  return aggregate;
}
